day59/Library/Library/urls.py
from django.conf.urls import url
from django.contrib import admin

from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^publisher_list/', views.publisher_list),
    # url(r'^publisher_add/', views.publisher_add),
    url(r'^publisher_add/', views.PublisherAdd.as_view()),
    # url(r'^publisher_add/', view),
    url(r'^publisher_del/', views.publisher_del),
    url(r'^publisher_edit/', views.publisher_edit),

    url(r'^book_list/', views.book_list),
    url(r'^book_add/', views.book_add),
    url(r'^book_del/', views.book_del),
    url(r'^book_edit/', views.book_edit),

    url(r'^author_list/', views.author_list),
    url(r'^author_add/', views.author_add),
    url(r'^author_del/', views.author_del),
    url(r'^author_edit/', views.author_edit),

    url(r'^file_upload/', views.file_upload),

]

day59/Library/app01/models.py
from django.db import models


# Create your models here.


class Publisher(models.Model):
    pid = models.AutoField(primary_key=True)  # pid 主键
    name = models.CharField(max_length=32, unique=True)
    addr = models.CharField(max_length=32, )

    def __str__(self):
        # return "《 {} - {} 》 ".format(self.pid, self.name)
        return "{}".format(self.name)


class Book(models.Model):
    title = models.CharField(max_length=32, unique=True)
    pub = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    # authors = models.ManyToManyField('Author')  # 不会生成字段  生成第三张表


class Author(models.Model):
    name = models.CharField(max_length=32)
    books = models.ManyToManyField('Book')  # 不会生成字段  生成第三张表

day59/Library/templates/author_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="" method="post">

    <p>
        姓名：<input type="text" name="author_name">
    </p>
    <p>作品：
        <select name="book_id" id="" multiple>
            {% for book in all_books %}
                <option value="{{ book.pk }}">{{ book.title }}</option>
            {% endfor %}

        </select>
    </p>
<button>提交</button>

</form>

</body>
</html>

day59/Library/templates/author_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="" method="post">

    <p>
        姓名：<input type="text" name="author_name" value="{{ author_obj.name }}">
    </p>
    <p>作品：
        <select name="book_id" id="" multiple>
            {% for book in all_books %}
                {% if book in author_obj.books.all %}
                    <option selected value="{{ book.pk }}">{{ book.title }}</option>
                {% else %}
                    <option value="{{ book.pk }}">{{ book.title }}</option>
                {% endif %}

            {% endfor %}

        </select>
    </p>
    <button>提交</button>

</form>

</body>
</html>

day59/Library/templates/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<table border="1">
    <thead>
    <tr>
        <th>序号</th>
        <th>姓名</th>
        <th>作品</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for author in all_authors %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ author.name }}</td>
            <td>
                {% for book in author.books.all %}
                    《{{ book.title }}》
                {% endfor %}

            </td>
            <td>
                <a href="/author_del/?pk={{ author.pk }}">删除</a>
                <a href="/author_edit/?pk={{ author.pk }}">编辑</a>
            </td>
        </tr>
    {% endfor %}


    </tbody>
</table>

</body>
</html>

day59/Library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}

{#    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">#}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.3.7-dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% get_static_prefix %}css/dsb.css">

    {% block css %}

    {% endblock %}

    <style>
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
            padding: 8px;
            line-height: 1.42857143;
            vertical-align: middle;
            border-top: 1px solid #ddd;
        }
    </style>

</head>
<body>

{% include 'nav.html' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li {% block pub_active %}  {% endblock %} ><a href="/publisher_list/">出版社列表</a></li>
                <li {% block book_active %}  {% endblock %}><a href="/book_list/">书籍列表</a></li>
                <li {% block author_active %}  {% endblock %}><a href="/author_list/">作者列表</a></li>

            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %}
                <h2>展示出版社</h2>
            {% endblock %}
        </div>
    </div>
</div>

{% block js %}

{% endblock %}
</body>
</html>

day59/Library/templates/book.html
{% extends 'base.html' %}

{% block css %}

{% endblock %}

{% block book_active %}
    class='active'
{% endblock %}

{% block content %}

    <h2 class="sub-header">展示书籍</h2>
    <a href="/book_add/" class="btn btn-sm btn-primary">添加</a>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>序号</th>
                <th>书名</th>
                <th>作者</th>
                <th>出版社</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for book in all_books %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>《{{ book.title }}》</td>
                    <td>
                        {% for author in  book.author_set.all %}
                            {{ author.name }}
                        {% endfor %}

                    </td>
                    <td>{{ book.pub }}</td>
                    <td>
                        <a class="btn btn-sm btn-danger" href="/book_del/?id={{ book.pk }}">删除</a>
                        <a class="btn btn-sm btn-success" href="/book_edit/?id={{ book.pk }}">编辑</a>

                    </td>
                </tr>

            {% endfor %}


            </tbody>

        </table>
    </div>

    {% load xxxx %}
    {% page 3 %}


{% endblock %}

day59/Library/templates/book_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/dsb.css">

    <style>
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
            padding: 8px;
            line-height: 1.42857143;
            vertical-align: middle;
            border-top: 1px solid #ddd;
        }
    </style>

</head>
<body>

{% include 'nav.html' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="/publisher_list/">出版社列表</a></li>
                <li class="active"><a href="/book_list/">书籍列表</a></li>
                {#            <li><a href="#">Analytics</a></li>#}
                {#            <li><a href="#">Export</a></li>#}
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">添加书籍</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post">
                        <div class="form-group {% if error %}has-error{% endif %} ">

                            <label for="inputEmail3" class="col-sm-2 col-sm-offset-1 control-label">书名：</label>
                            <div class="col-sm-6">
                                <input type="text" name="book_name" class="form-control" id="inputEmail3">

                                <span class="help-block">{{ error }} </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-sm-offset-1 control-label">出版社：</label>
                            <div class="col-sm-6">
                                <select name="pub_id" id="" class="form-control">
                                    {% for publisher in all_publisher %}
                                        <option value="{{ publisher.pk }}">{{ publisher.name }}</option>
                                    {% endfor %}

                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-default">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>


</body>
</html>

day59/Library/templates/book_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/dsb.css">

    <style>
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
            padding: 8px;
            line-height: 1.42857143;
            vertical-align: middle;
            border-top: 1px solid #ddd;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="/publisher_list/">出版社列表</a></li>
                <li class="active"><a href="/book_list/">书籍列表</a></li>
                {#            <li><a href="#">Analytics</a></li>#}
                {#            <li><a href="#">Export</a></li>#}
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">添加书籍</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post">
                        <div class="form-group {% if error %}has-error{% endif %} ">

                            <label for="inputEmail3" class="col-sm-2 col-sm-offset-1 control-label">书名：</label>
                            <div class="col-sm-6">
                                <input type="text" name="book_name" class="form-control" id="inputEmail3"
                                       value="{{ book_obj.title }}">

                                <span class="help-block">{{ error }} </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-sm-offset-1 control-label">出版社：</label>
                            <div class="col-sm-6">
                                <select name="pub_id" id="" class="form-control">
                                    {% for publisher in all_publisher %}

                                        {% if book_obj.pub == publisher %}
                                            <option selected value="{{ publisher.pk }}">{{ publisher.name }}</option>
                                        {% else %}
                                            <option value="{{ publisher.pk }}">{{ publisher.name }}</option>
                                        {% endif %}

                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-default">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>


</body>
</html>

day59/Library/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/dsb.css">

    <style>
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
            padding: 8px;
            line-height: 1.42857143;
            vertical-align: middle;
            border-top: 1px solid #ddd;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="/publisher_list/">出版社列表</a></li>
                <li class="active"><a href="/book_list/">书籍列表</a></li>
                {#            <li><a href="#">Analytics</a></li>#}
                {#            <li><a href="#">Export</a></li>#}
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">展示书籍</h2>
            <a href="/book_add/" class="btn btn-sm btn-primary">添加</a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>书名</th>
                        <th>作者</th>
                        <th>出版社</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for book in all_books %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>《{{ book.title }}》</td>
                            <td>
                                {% for author in  book.author_set.all  %}
                                    {{ author.name }}
                                {% endfor %}

                            </td>
                            <td>{{ book.pub }}</td>
                            <td>
                                <a  class="btn btn-sm btn-danger" href="/book_del/?id={{ book.pk }}">删除</a>
                                <a  class="btn btn-sm btn-success"  href="/book_edit/?id={{ book.pk }}">编辑</a>

                            </td>
                        </tr>

                    {% endfor %}


                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>


</body>
</html>

day59/Library/templates/file_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="f1">
    <button>上传</button>
</form>

</body>
</html>

day59/Library/templates/page.html
<nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
      {% for i in num %}
          <li><a href="#">{{ i }}</a></li>
      {% endfor %}

    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

day59/Library/templates/publisher.html
{% extends 'base.html' %}

{% block pub_active %}
    class='active'
{% endblock %}

{% block content %}

    <h2 class="sub-header">展示出版社</h2>
    <a href="/publisher_add/" class="btn btn-sm btn-primary">添加</a>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>序号</th>
                <th>id</th>
                <th>出版社名称</th>
                <th>出版社地址</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for pub in k1 %}
                <tr>
                    <td> {{ forloop.counter }}  </td>
                    <td>{{ pub.pid }}</td>
                    <td>{{ pub.name }}</td>
                    <td>{{ pub.addr }}</td>
                    <td>
                        <a class="btn btn-danger btn-sm" href="/publisher_del/?id={{ pub.pid }}">删除 </a>
                        <a class="btn btn-success btn-sm" href="/publisher_edit/?id={{ pub.pid }}">编辑 </a>
                    </td>
                </tr>
            {% endfor %}


            </tbody>

        </table>
    </div>

    {% load xxxx %}
    {% page 10 %}
{% endblock %}

day59/Library/templates/publisher_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/dsb.css">

    <style>
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
            padding: 8px;
            line-height: 1.42857143;
            vertical-align: middle;
            border-top: 1px solid #ddd;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Reports</a></li>
                {#            <li><a href="#">Analytics</a></li>#}
                {#            <li><a href="#">Export</a></li>#}
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">添加出版社</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="application/x-www-form-urlencoded">
                        <div class="form-group {% if error %}has-error{% endif %} ">

                            <label for="inputEmail3" class="col-sm-2 col-sm-offset-1 control-label">出版社名称</label>
                            <div class="col-sm-6">
                                <input type="text" name="pub_name"  class="form-control" id="inputEmail3" placeholder="请输入出版社名称">

                                <span class="help-block" >{{ error }} </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-sm-offset-1 control-label">出版社地址</label>
                            <div class="col-sm-6">
                                <input type="text" name="pub_addr"  class="form-control" id="inputPassword3" >
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-default">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>


</body>
</html>

day59/Library/templates/publisher_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/dsb.css">

    <style>
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
            padding: 8px;
            line-height: 1.42857143;
            vertical-align: middle;
            border-top: 1px solid #ddd;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Reports</a></li>
                {#            <li><a href="#">Analytics</a></li>#}
                {#            <li><a href="#">Export</a></li>#}
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">添加出版社</h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post">
                        <div class="form-group {% if error %}has-error{% endif %} ">
                            <label for="inputEmail3" class="col-sm-2 col-sm-offset-1 control-label">出版社名称</label>
                            <div class="col-sm-6">
                                <input type="text" name="pub_name"  class="form-control"  value="{{ pub_obj.name }}" id="inputEmail3" placeholder="请输入出版社名称">

                                <span class="help-block">{{ error }} </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 col-sm-offset-1 control-label">出版社地址</label>
                            <div class="col-sm-6">
                                <input type="text" name="pub_addr"  value="{{ pub_obj.addr }}" class="form-control" id="inputPassword3" >
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-default">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>


</body>
</html>

day59/Library/templates/publisher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/dsb.css">

    <style>
        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
            padding: 8px;
            line-height: 1.42857143;
            vertical-align: middle;
            border-top: 1px solid #ddd;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li  class="active"><a href="/publisher_list/">出版社列表</a></li>
                <li><a href="/book_list/">书籍列表</a></li>
                {#            <li><a href="#">Analytics</a></li>#}
                {#            <li><a href="#">Export</a></li>#}
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">展示出版社</h2>
            <a href="/publisher_add/" class="btn btn-sm btn-primary">添加</a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>id</th>
                        <th>出版社名称</th>
                        <th>出版社地址</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for pub in k1 %}
                        <tr>
                            <td> {{ forloop.counter }}  </td>
                            <td>{{ pub.pid }}</td>
                            <td>{{ pub.name }}</td>
                            <td>{{ pub.addr }}</td>
                            <td>
                                <a class="btn btn-danger btn-sm" href="/publisher_del/?id={{ pub.pid }}">删除 </a>
                                <a class="btn btn-success btn-sm" href="/publisher_edit/?id={{ pub.pid }}">编辑 </a>
                            </td>
                        </tr>
                    {% endfor %}


                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>


</body>
</html>