day74/tf_crm/app01/urls.py
from django.conf.urls import url
from app01 import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^customer/$', views.Customer.as_view(), name='customer'),
    url(r'^my_customer/$', views.Customer.as_view(), name='my_customer'),
    # url(r'^customer_add/$', views.customer_add, name='customer_add'),
    # url(r'^customer_edit/(\d+)/$', views.customer_edit, name='customer_edit'),
    url(r'^customer_add/$', views.customer_change, name='customer_add'),
    url(r'^customer_edit/(\d+)/$', views.customer_change, name='customer_edit'),
    #  展示某个销售的所有的跟进记录
    url(r'^consult_record/$', views.ConsultRecordList.as_view(), name='consult_record'),
    #  展示某个客户的所有的跟进记录
    url(r'^consult_record/(?P<customer_id>\d+)/$', views.ConsultRecordList.as_view(), name='one_consult_record'),

    url(r'^consult_record_add/$', views.consult_record_change, name='consult_record_add'),
    url(r'^consult_record_edit/(\d+)/$', views.consult_record_change, name='consult_record_edit'),

    url(r'^enrollment_list/$', views.EnrollmentList.as_view(), name='enrollment_list'),
    url(r'^enrollment_list/(?P<customer_id>\d+)/$', views.EnrollmentList.as_view(), name='one_enrollment_list'),

    url(r'^enrollment_add/(?P<customer_id>\d+)$', views.enrollment_change, name='enrollment_add'),
    url(r'^enrollment_edit/(?P<pk>\d+)$', views.enrollment_change, name='enrollment_edit'),

]

day74/tf_crm/tf_crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app01.urls')),
]

day74/tf_crm/app01/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)

pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128)
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)

    def show_class(self):
        return ','.join([str(i) for i in self.class_list.all()])

    def show_status(self):
        """
        ('signed', "已报名"),
         ('unregistered', "未报名"),
         ('studying', '学习中'),
         ('paid_in_full', "学费已交齐")
        :return:
        """
        color_dict = {
            'signed': 'green',
            'unregistered': 'red',
            'studying': 'yellow',
            'paid_in_full': 'blue',
        }

        return mark_safe(
            '<span style="background-color: {};color: white;padding: 3px">{}</span>'.format(color_dict.get(self.status),
                                                                                            self.get_status_display()))

    def __str__(self):
        return  self.name if self.name else '--'



class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}{}".format(self.campuses, self.get_course_display(), self.semester)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserProfile', related_name='course_record', verbose_name="讲师")
    recorder = models.ForeignKey('UserProfile', verbose_name="记录者")

    class Meta:
        unique_together = ('re_class', 'day_num')


class StudyRecord(models.Model):
    """
    学习记录
    """

day74/tf_crm/templates/consult_record.html
{% extends 'layout.html' %}

{% load my_tags %}

{% block content %}

    <a class="btn btn-primary btn-sm" href="{% reverse_url request 'consult_record_add' %}">新增</a>
    <div>
        <form action="" class="form-inline pull-right">
            <input type="text" name="query" class="form-control">
            <button class="btn btn-success btn-sm">搜索</button>
        </form>
    </div>

    <form action="" method="post" class="form-inline">
        <select name="action" id="" class="form-control">
        </select>
        <button class="btn btn-success btn-sm">提交</button>
        {% csrf_token %}
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>客户</th>
                <th>跟进内容</th>
                <th>跟进状态</th>
                <th>跟进日期</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for consult_record in all_consult_records %}
                <tr>
                    <td><input type="checkbox" name="pk" value="{{ customer.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ consult_record.customer }}</td>
                    <td>{{ consult_record.note|truncatechars:60 }}</td>
                    <td>{{ consult_record.get_status_display }}</td>
                    <td>{{ consult_record.date }}</td>

                    <td><a class="btn btn-info btn-sm" href="{% reverse_url request 'consult_record_edit' consult_record.pk %}">编辑</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </form>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ page_html }}
        </ul>
    </nav>
{% endblock %}

day74/tf_crm/templates/customer.html
{% extends 'layout.html' %}

{% load my_tags %}

{% block content %}

    <a class="btn btn-primary btn-sm" href="{% url 'customer_add' %}">新增</a>
    <div>
        <form action="" class="form-inline pull-right">
            {#            <select name="query_field" class="form-control" >#}
            {#                <option value="name">姓名</option>#}
            {#                <option value="phone">手机号</option>#}
            {#                <option value="qq">QQ</option>#}
            {##}
            {#            </select>#}
            <input type="text" name="query" class="form-control">
            <button class="btn btn-success btn-sm">搜索</button>
        </form>
    </div>

    <form action="" method="post" class="form-inline">
        <select name="action" id="" class="form-control">
            {% if request.path_info ==  url %}
                <option value="multi_apply">公户转私户</option>
            {% else %}
                <option value="multi_pub">私户转公户</option>
            {% endif %}

        </select>
        <button class="btn btn-success btn-sm">提交</button>
        {% csrf_token %}
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>姓名</th>
                <th>QQ</th>
                <th>性别</th>
                <th>出生日期</th>
                <th>手机号</th>
                <th>客户来源</th>
                <th>咨询课程</th>
                <th>班级类型</th>
                <th>状态</th>
                <th>跟进记录</th>
                <th>报名记录</th>
                <th>销售</th>
                <th>班级</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in all_customer %}
                <tr>
                    <td><input type="checkbox" name="pk" value="{{ customer.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ customer.name|default:'-' }}</td>
                    <td>{{ customer.qq }}</td>
                    <td>{{ customer.get_sex_display }}</td>
                    <td>{{ customer.birthday }}</td>
                    <td>{{ customer.phone }}</td>
                    <td>{{ customer.get_source_display }}</td>
                    <td>{{ customer.course }}</td>
                    <td>{{ customer.get_class_type_display }}</td>
                    <td> {{ customer.show_status }} </td>
                    <td><a href="{% url 'one_consult_record' customer.pk %}">查看</a> </td>
                    <td>
                        <a href="{% reverse_url request 'enrollment_add' customer_id=customer.pk %}">新增</a>
                        <a href="{% url 'one_enrollment_list' customer.pk %}">查看</a>
                    </td>
                    <td>{{ customer.consultant }}</td>
                    <td> {{ customer.show_class }}
                        {#                {% for class_list in customer.class_list.all  %}#}
                        {#                    {{ class_list }}#}
                        {#                {% endfor %}#}
                    </td>
                    <td><a class="btn btn-info btn-sm" href="{% reverse_url request 'customer_edit' customer.pk  %}">编辑</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </form>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ page_html }}
        </ul>
    </nav>
{% endblock %}

day74/tf_crm/templates/customer_add.html
{% extends 'layout.html' %}

{% block css %}

    <style>
        .not-required {
            color: #a9a6a6;
        }

    </style>

{% endblock %}


{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">新增客户</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" action="" novalidate>
                {% csrf_token %}

                {% for field in form_obj %}

                    <div class="form-group{% if field.errors %} has-error{% endif %}">

                        <label for="{{ field.id_for_label }}"
                               class="col-sm-2 col-sm-offset-1 control-label{% if not field.field.required %} not-required  {% endif %}">{{ field.label }}</label>
                        <div class="col-sm-6">
                            {{ field }}

                            <span class="help-block"> {{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}


                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

day74/tf_crm/templates/customer_change.html
{% extends 'layout.html' %}

{% block css %}

    <style>
        .not-required {
            color: #a9a6a6;
        }

    </style>

{% endblock %}


{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" action="" novalidate>
                {% csrf_token %}

                {% for field in form_obj %}

                    <div class="form-group{% if field.errors %} has-error{% endif %}">

                        <label for="{{ field.id_for_label }}"
                               class="col-sm-2 col-sm-offset-1 control-label{% if not field.field.required %} not-required  {% endif %}">{{ field.label }}</label>
                        <div class="col-sm-6">
                            {{ field }}
                            <span class="help-block"> {{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}


                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

day74/tf_crm/templates/customer_edit.html
{% extends 'layout.html' %}

{% block css %}

    <style>
        .not-required {
            color: #a9a6a6;
        }

    </style>

{% endblock %}


{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">编辑客户</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" action="" novalidate>
                {% csrf_token %}

                {% for field in form_obj %}

                    <div class="form-group{% if field.errors %} has-error{% endif %}">

                        <label for="{{ field.id_for_label }}"
                               class="col-sm-2 col-sm-offset-1 control-label{% if not field.field.required %} not-required  {% endif %}">{{ field.label }}</label>
                        <div class="col-sm-6">
                            {{ field }}
                            <span class="help-block"> {{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}


                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

day74/tf_crm/templates/enrollment_list.html
{% extends 'layout.html' %}

{% load my_tags %}

{% block content %}


    <div>
        <form action="" class="form-inline pull-right">
            <input type="text" name="query" class="form-control">
            <button class="btn btn-success btn-sm">搜索</button>
        </form>
    </div>

    <form action="" method="post" class="form-inline">
        <select name="action" id="" class="form-control">
        </select>
        <button class="btn btn-success btn-sm">提交</button>
        {% csrf_token %}
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>客户名称</th>
                <th>报名原因</th>
                <th>期望</th>
                <th>报名日期</th>
                <th>校区</th>
                <th>班级</th>

                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for enrollment in all_enrollments %}
                <tr>
                    <td><input type="checkbox" name="pk" value="{{ customer.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ enrollment.customer }}</td>
                    <td>{{ enrollment.why_us }}</td>
                    <td>{{ enrollment.your_expectation }}</td>
                    <td>{{ enrollment.enrolled_date }}</td>
                    <td>{{ enrollment.school }}</td>
                    <td>{{ enrollment.enrolment_class }}</td>


                    <td><a class="btn btn-info btn-sm" href="{% reverse_url request 'enrollment_edit' enrollment.pk %}">编辑</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </form>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ page_html }}
        </ul>
    </nav>
{% endblock %}

day74/tf_crm/templates/form.html
{% extends 'layout.html' %}

{% block css %}

    <style>
        .not-required {
            color: #a9a6a6;
        }

    </style>

{% endblock %}


{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" action="" novalidate>
                {% csrf_token %}

                {% for field in form_obj %}

                    <div class="form-group{% if field.errors %} has-error{% endif %}">

                        <label for="{{ field.id_for_label }}"
                               class="col-sm-2 col-sm-offset-1 control-label{% if not field.field.required %} not-required  {% endif %}">{{ field.label }}</label>
                        <div class="col-sm-6">
                            {{ field }}
                            <span class="help-block"> {{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <p class="text-center text-danger"> {{ form_obj.non_field_errors.0 }} </p>


                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

day74/tf_crm/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>登陆</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="login-container">
    <h1>ShareLink</h1>
    <div class="connect">
        <p>Link the world. Share to world.</p>
    </div>
    <form action="" method="post" id="loginForm" novalidate="novalidate">
        {% csrf_token %}
        <div>
            <input type="text" name="username" class="username" placeholder="用户名" autocomplete="off" >
        </div>
        <div>
            <input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false"
                   onpaste="return false">
        </div>
        <div>{{ error }}</div>

        <button id="submit" type="submit">登 陆</button>
    </form>
    <a href="{% url 'register' %}">
        <button type="button" class="register-tis">还有没有账号？</button>
    </a>
</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

<script src="{% static 'js/supersized.3.2.7.min.js' %}"></script>

<script>
    jQuery(function ($) {
        $.supersized({
            slide_interval: 4000,
            transition: 1,
            transition_speed: 1000,
            performance: 1,
            min_width: 0,
            min_height: 0,
            vertical_center: 1,
            horizontal_center: 1,
            fit_always: 0,
            fit_portrait: 1,
            fit_landscape: 0,
            slide_links: 'blank',
            slides: [{image: "{% static 'imgs/1.jpg' %}"}, {image: "{% static 'imgs/2.jpg' %}"}, {image: "{% static 'imgs/3.jpg' %}"}]
        });
    });
</script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>



</body>
</html>

day74/tf_crm/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>注册</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        select {
            width: 300px;
            height: 42px;
            line-height: 42px;
            margin-top: 25px;
            padding: 0 15px;
            background: #2d2d2d;
            background: rgba(45, 45, 45, .15);
            -moz-border-radius: 6px;
            -webkit-border-radius: 6px;
            border-radius: 6px;
            border: 1px solid #3d3d3d;
            border: 1px solid rgba(255, 255, 255, .15);
            -moz-box-shadow: 0 2px 3px 0 rgba(0, 0, 0, .1) inset;
            -webkit-box-shadow: 0 2px 3px 0 rgba(0, 0, 0, .1) inset;
            box-shadow: 0 2px 3px 0 rgba(0, 0, 0, .1) inset;
            font-family: microsoft yahei, Helvetica, Arial, sans-serif;
            font-size: 14px;
            color: #fff;
            text-shadow: 0 1px 2px rgba(0, 0, 0, .1);
            -o-transition: all .2s;
            -moz-transition: all .2s;
            -webkit-transition: all .2s;
            -ms-transition: all .2s;

        }


        option {
            background-color: #2d2d2d;
        }
    </style>

</head>
<body>
<div class="login-container">
    <h1>ShareLink</h1>
    <div class="connect">
        <p>Link the world. Share to world.</p>
    </div>
    <form action="" method="post" id="loginForm" novalidate="novalidate">
        {% csrf_token %}

        <div>
            {{ form_obj.username }}
        </div>
        <div>
            {{ form_obj.username.errors.0 }}
        </div>
        <div>
            {{ form_obj.password }}
        </div>
        <div>
            {{ form_obj.password.errors.0 }}
        </div>
        <div>
            {{ form_obj.re_password }}
        </div>
        <div>
            {{ form_obj.re_password.errors.0 }}
        </div>
        <div>
            {{ form_obj.name }}
        </div>
        <div>
            {{ form_obj.name.errors.0 }}
        </div>
        <div>
            {{ form_obj.department }}
        </div>
        <div>
            {{ form_obj.department.errors.0 }}
        </div>
        <div>
            {{ form_obj.mobile }}
        </div>
        <div>
            {{ form_obj.mobile.errors.0 }}
        </div>


        <button id="submit" type="submit">注 册</button>
    </form>
    <a href="{% url 'login' %}">
        <button type="button" class="register-tis">已有账号，点击登录</button>
    </a>
</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

<script src="{% static 'js/supersized.3.2.7.min.js' %}"></script>

<script>
    jQuery(function ($) {
        $.supersized({
            slide_interval: 4000,
            transition: 1,
            transition_speed: 1000,
            performance: 1,
            min_width: 0,
            min_height: 0,
            vertical_center: 1,
            horizontal_center: 1,
            fit_always: 0,
            fit_portrait: 1,
            fit_landscape: 0,
            slide_links: 'blank',
            slides: [{image: "{% static 'imgs/1.jpg' %}"}, {image: "{% static 'imgs/2.jpg' %}"}, {image: "{% static 'imgs/3.jpg' %}"}]
        });
    });
</script>
{#<script src="{% static 'js/jquery.validate.min.js' %}"></script>#}


</body>
</html>