day79/luffy_permission/luffy_permission/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls')),
    url(r'^rbac/', include('rbac.urls',namespace='rbac')),
]

day79/luffy_permission/rbac/urls.py
from django.conf.urls import url, include

from rbac import views

urlpatterns = [

    url(r'^role/list/$', views.role_list, name='role_list'),
    url(r'^role/add/$', views.role_change, name='role_add'),
    url(r'^role/edit/(\d+)$', views.role_change, name='role_edit'),

    url(r'^menu/list/$', views.menu_list, name='menu_list'),
    url(r'^menu/add/$', views.menu_change, name='menu_add'),
    url(r'^menu/edit/(\d+)$', views.menu_change, name='menu_edit'),

    url(r'^permission/add/$', views.permission_change, name='permission_add'),
    url(r'^permission/edit/(\d+)$', views.permission_change, name='permission_edit'),

    url(r'^(\w+)/delete/(\d+)$', views.delete, name='delete'),

    url(r'^multi/permissions/$', views.multi_permissions, name='multi_permissions'),

    url(r'^distribute/permissions/$', views.distribute_permissions, name='distribute_permissions'),

]

day79/luffy_permission/web/urls.py
from django.conf.urls import url
from web.views import customer
from web.views import payment
from web.views import account

urlpatterns = [

    url(r'^login/$', account.login, name='login'),
    url(r'^index/$', account.index, name='index'),

    url(r'^customer/list/$', customer.customer_list, name='customer_list'),
    url(r'^customer/add/$', customer.customer_add,name='customer_add'),
    url(r'^customer/edit/(?P<cid>\d+)/$', customer.customer_edit,name='customer_edit'),
    url(r'^customer/del/(?P<cid>\d+)/$', customer.customer_del,name='customer_del'),

    url(r'^payment/list/$', payment.payment_list,name='payment_list'),
    url(r'^payment/add/$', payment.payment_add,name='payment_add'),
    url(r'^payment/edit/(?P<pid>\d+)/$', payment.payment_edit,name='payment_edit'),
    url(r'^payment/del/(?P<pid>\d+)/$', payment.payment_del,name='payment_del'),
]

day79/luffy_permission/rbac/models.py
from django.db import models


class Menu(models.Model):
    """
    一级菜单
    """
    title = models.CharField(max_length=32, verbose_name='一级标题')
    icon = models.CharField(max_length=64, verbose_name='图标', default='fa-connectdevelop')
    weight = models.IntegerField(default=1,verbose_name='权重')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "菜单表"
        verbose_name_plural = verbose_name


class Permission(models.Model):
    """
    权限表
    有menu_id     二级菜单
    没有menu_id   普通权限

    有parent_id   子权限
    没有parent_id  父权限  二级菜单

    """
    url = models.CharField(max_length=200, verbose_name='权限')
    title = models.CharField(max_length=32, verbose_name='标题')
    name = models.CharField(max_length=32, verbose_name='url的别名',unique=True)
    menu = models.ForeignKey('Menu', blank=True, null=True)
    parent = models.ForeignKey('Permission', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "权限表"
        verbose_name_plural = verbose_name


class Role(models.Model):
    name = models.CharField(max_length=32, verbose_name="角色名")
    permissions = models.ManyToManyField('Permission', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "角色表"
        verbose_name_plural = verbose_name


class User(models.Model):
    username = models.CharField(max_length=32, verbose_name="用户名")
    password = models.CharField(max_length=32, verbose_name="密码")
    roles = models.ManyToManyField('Role', blank=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户表"
        verbose_name_plural = verbose_name

day79/luffy_permission/rbac/service/routes.py
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls import RegexURLResolver, RegexURLPattern
from collections import OrderedDict


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    """
    None  '/'
     [
        url(r'^', include('web.urls')),
        #  url(r'^rbac/', include('rbac.urls',namespace='rbac')),
    ]



    """

    """
     None  '/^'   
     [
        
            url(r'^login/$', account.login, name='login'),
            url(r'^index/$', account.index, name='index'),
        
            url(r'^customer/list/$', customer.customer_list, name='customer_list'),
            url(r'^customer/add/$', customer.customer_add,name='customer_add'),
            url(r'^customer/edit/(?P<cid>\d+)/$', customer.customer_edit,name='customer_edit'),
            url(r'^customer/del/(?P<cid>\d+)/$', customer.customer_del,name='customer_del'),
        
            url(r'^payment/list/$', payment.payment_list,name='payment_list'),
            url(r'^payment/add/$', payment.payment_add,name='payment_add'),
            url(r'^payment/edit/(?P<pid>\d+)/$', payment.payment_edit,name='payment_edit'),
            url(r'^payment/del/(?P<pid>\d+)/$', payment.payment_del,name='payment_del'),
        ]
    
    """

    for item in urlpatterns:
        if isinstance(item, RegexURLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = pre_namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:
                    namespace = None
            #  None  '/^'
            recursion_urls(namespace, pre_url + item.regex.pattern, item.url_patterns, url_ordered_dict)
        else:

            if pre_namespace:
                name = "%s:%s" % (pre_namespace, item.name,)
            else:
                name = item.name
            if not item.name:
                raise Exception('URL路由中必须设置name属性')
            #  '/^^login/$'   '/login/'
            url = pre_url + item._regex
            url_ordered_dict[name] = {'name': name, 'url': url.replace('^', '').replace('$', '')}


def get_all_url_dict(ignore_namespace_list=None):
    """
    获取路由中
    :return:
    """
    ignore_list = ignore_namespace_list or []
    url_ordered_dict = OrderedDict()

    md = import_string(settings.ROOT_URLCONF)  # 'luffy_permission.urls'
    urlpatterns = []

    """
     [
        url(r'^admin/', admin.site.urls),
        url(r'^', include('web.urls')),
        #  url(r'^rbac/', include('rbac.urls',namespace='rbac')),
    ]
    视图                  RegexURLPattern
    路由分发 include      RegexURLResolver

    """

    for item in md.urlpatterns:
        if isinstance(item, RegexURLResolver) and item.namespace in ignore_list:
            continue
        urlpatterns.append(item)
    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    return url_ordered_dict

day79/luffy_permission/rbac/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from rbac import models
from .forms import RoleForm, MenuForm, PermissionForm, MultiPermissionForm


# Create your views here.
def role_list(request):
    all_roles = models.Role.objects.all()
    return render(request, 'rbac/role_list.html', {'all_roles': all_roles})


def role_change(request, pk=None):
    obj = models.Role.objects.filter(pk=pk).first()
    form_obj = RoleForm(instance=obj)
    if request.method == 'POST':
        print('xxx')
        form_obj = RoleForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('rbac:role_list'))

    return render(request, 'rbac/form.html', {'form_obj': form_obj})


def delete(request, table, pk):
    model_class = getattr(models, table.capitalize())
    if not model_class:
        return HttpResponse('要删除的表不存在')

    obj = model_class.objects.filter(pk=pk).first()
    if not obj:
        return HttpResponse('要删除的数据不存在')
    obj.delete()
    referer = request.META.get('HTTP_REFERER')
    return redirect(referer)


from django.db.models import Q


def menu_list(request):
    mid = request.GET.get('mid')

    all_menus = models.Menu.objects.all()
    if mid:
        all_permissions = models.Permission.objects.filter(Q(parent__menu_id=mid) | Q(menu_id=mid))
    else:
        all_permissions = models.Permission.objects.all()

    all_permissions = all_permissions.values('title', 'url', 'name', 'menu_id', 'id', 'menu__title', 'parent_id')
    permission_dict = {}

    for i in all_permissions:
        if i.get('menu_id'):
            permission_dict[i['id']] = i
            i['children'] = []

    for i in all_permissions:
        if i.get('parent_id'):
            permission_dict[i['parent_id']]['children'].append(i)

    print(permission_dict)
    return render(request, 'rbac/menu_list.html',
                  {"mid": mid, 'all_menus': all_menus, 'all_permissions': permission_dict})


def menu_change(request, pk=None):
    obj = models.Menu.objects.filter(pk=pk).first()
    form_obj = MenuForm(instance=obj)
    if request.method == 'POST':
        form_obj = MenuForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('rbac:menu_list'))

    return render(request, 'rbac/menu_form.html', {'form_obj': form_obj})


def permission_change(request, pk=None):
    obj = models.Permission.objects.filter(pk=pk).first()
    form_obj = PermissionForm(instance=obj)
    if request.method == 'POST':
        form_obj = PermissionForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('rbac:menu_list'))

    return render(request, 'rbac/form.html', {'form_obj': form_obj})


from django.forms import modelformset_factory, formset_factory
from rbac.service.routes import get_all_url_dict


def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """
    post_type = request.GET.get('type')
    # 编辑和删除的formset
    FormSet = modelformset_factory(models.Permission, MultiPermissionForm, extra=0)
    # 新增的formset
    AddFormSet = formset_factory(MultiPermissionForm, extra=0)
    # 数据库中所有的权限
    permissions = models.Permission.objects.all()
    # 路由系统中所有的权限
    router_dict = get_all_url_dict(ignore_namespace_list=['admin', ])
    # 数据库中权限别名的集合
    permissions_name_set = set([i.name for i in permissions])
    # 路由系统中权限别名的集合
    router_name_set = set(router_dict.keys())

    #  新增的nameset
    add_name_set = router_name_set - permissions_name_set
    add_formset = AddFormSet(initial=[row for name, row in router_dict.items() if name in add_name_set])

    if request.method == 'POST' and post_type == 'add':
        add_formset = AddFormSet(request.POST)
        if add_formset.is_valid():
            permission_obj_list = [models.Permission(**i) for i in add_formset.cleaned_data]
            query_list = models.Permission.objects.bulk_create(permission_obj_list)
            add_formset = AddFormSet()
            for i in query_list:
                permissions_name_set.add(i.name)
    #  删除的nameset
    del_name_set = permissions_name_set - router_name_set
    del_formset = FormSet(queryset=models.Permission.objects.filter(name__in=del_name_set))
    #  更新的nameset
    update_name_set = permissions_name_set & router_name_set
    update_formset = FormSet(queryset=models.Permission.objects.filter(name__in=update_name_set))

    if request.method == 'POST' and post_type == 'update':
        update_formset = FormSet(request.POST)
        if update_formset.is_valid():
            update_formset.save()
            update_formset = FormSet(queryset=models.Permission.objects.filter(name__in=update_name_set))

    return render(
        request,
        'rbac/multi_permissions.html',
        {
            'del_formset': del_formset,
            'update_formset': update_formset,
            'add_formset': add_formset,
        }
    )


def distribute_permissions(request):
    """
    分配权限
    :param request:
    :return:
    """
    uid = request.GET.get('uid')  # 用户id
    rid = request.GET.get('rid')  # 角色id

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        user = models.User.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        user.roles.set(request.POST.getlist('roles'))

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = models.Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permissions.set(request.POST.getlist('permissions'))

    # 所有的用户
    user_list = models.User.objects.all()
    # 一个用户的角色的id
    user_has_roles = models.User.objects.filter(id=uid).values('id', 'roles')
    print(user_has_roles)
    # 用户的角色id的字典   { 角色的id : none }
    user_has_roles_dict = { item['roles']: None for item in user_has_roles }
    # 所有的角色
    role_list = models.Role.objects.all()

    if rid:
        role_has_permissions = models.Role.objects.filter(id=rid, permissions__id__isnull=False).values('id',
                                                                                                        'permissions')
    elif uid and not rid:
        user = models.User.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        role_has_permissions = user.roles.filter(permissions__id__isnull=False).values('id', 'permissions')
    else:
        role_has_permissions = []

    # 用户所拥有的所有的权限的id  { 权限的id : none }
    role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}

    all_menu_list = []
    """
     all_menu_list = [ 
     { id  title  children:[
          { 'id', 'title', 'menu_id' 'children': [
                   {'id', 'title', 'parent_id'}
          ] }, 
     ] } 
     {'id': None, 'title': '其他', 'children': [
           {'id', 'title', 'parent_id'}
     ]}
     ]
    """

    queryset = models.Menu.objects.values('id', 'title')
    menu_dict = {}
    """
    menu_dict = { 
        一级菜单的id :{ id  title  children:[
               { 'id', 'title', 'menu_id' 'children': [
                   {'id', 'title', 'parent_id'}
               ] }, 
        
        ]  } ,
        None : {'id': None, 'title': '其他', 'children': [
                       {'id', 'title', 'parent_id'}
            ]}
         } 
    """

    for item in queryset:
        item['children'] = []
        menu_dict[item['id']] = item
        all_menu_list.append(item)

    other = {'id': None, 'title': '其他', 'children': []}
    all_menu_list.append(other)
    menu_dict[None] = other

    root_permission = models.Permission.objects.filter(menu__isnull=False).values('id', 'title', 'menu_id')
    root_permission_dict = {}
    """
    root_permission_dict = { 
        父权限的id : { 'id', 'title', 'menu_id' 'children': [
                {'id', 'title', 'parent_id'}
        ] }
    }
    
    """
    for per in root_permission:
        per['children'] = []
        nid = per['id']
        menu_id = per['menu_id']
        root_permission_dict[nid] = per
        menu_dict[menu_id]['children'].append(per)

    node_permission = models.Permission.objects.filter(menu__isnull=True).values('id', 'title', 'parent_id')

    for per in node_permission:
        pid = per['parent_id']
        if not pid:
            menu_dict[None]['children'].append(per)
            continue
        root_permission_dict[pid]['children'].append(per)

    return render(
        request,
        'rbac/distribute_permissions.html',
        {
            'user_list': user_list,
            'role_list': role_list,
            'user_has_roles_dict': user_has_roles_dict,
            'role_has_permissions_dict': role_has_permissions_dict,
            'all_menu_list': all_menu_list,
            'uid': uid,
            'rid': rid
        }
    )

day79/luffy_permission/rbac/templates/rbac/breadcrumb.html
<div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

        {% for breadcrumb in request.breadcrumb_list %}
            {% if forloop.last %}
                <li class="active">{{ breadcrumb.title }}</li>
            {% else %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.title }} </a></li>
            {% endif %}


        {% endfor %}

    </ol>
</div>

day79/luffy_permission/rbac/templates/rbac/form.html
{% extends 'layout.html' %}




{% block content %}

    <div class="col-sm-8 col-sm-offset-2" style="margin-top: 50px">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}

            {% for field in form_obj %}
                <div class="form-group {% if field.errors %} has-error {% endif %}">

                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        <span class="help-block">{{ field.errors.0 }}</span>

                    </div>
                </div>
            {% endfor %}
            <p class="text-center text-danger"> {{ form_obj.non_field_errors.0 }} </p>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">保存</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

day79/luffy_permission/rbac/templates/rbac/menu.html
<div class="static-menu">
    {% for menu in menu_list %}
        <a href="{{ menu.url }}" class="{{ menu.class }}" >
            <span class="icon-wrap"><i class="fa {{ menu.icon }}"></i></span> {{ menu.title }}</a>
    {% endfor %}
</div>

day79/luffy_permission/rbac/templates/rbac/menu2.html
<div class="multi-menu">
    {% for menu in menu_list %}
        <div class="item">
            <div class="title"><i class="fa {{ menu.icon }}"></i> {{ menu.title }}</div>
            <div class="body {{ menu.class }} ">
                {% for child in menu.children %}
                    <a href="{{ child.url }}"  class="{{ child.class }}"> {{ child.title }} </a>
                {% endfor %}

            </div>

        </div>
    {% endfor %}


</div>

day79/luffy_permission/rbac/templates/rbac/menu_list.html
{% extends 'layout.html' %}


{% block css %}
    <style>
        .permission-area tr.root {
            background-color: #f1f7fd;;
        }

        .menu-body tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }


    </style>

{% endblock %}

{% block content %}
    <div style="margin-top: 20px">

        <div class="col-sm-3">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-book"></i> 菜单管理
                    <a href="{% url 'rbac:menu_add' %}" class="btn btn-sm btn-success pull-right"
                       style="padding: 2px 7px;margin-top: -2px"> <i
                            class="fa fa-plus"></i> 添加</a></div>

                <table class="table  table-hover">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>图标</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody class="menu-body">

                    {% for menu in all_menus %}
                        <tr {% if mid == menu.pk|safe %}class="active"{% endif %}>


                            <td><a href="?mid={{ menu.pk }}">{{ menu.title }}</a></td>
                            <td><i class="fa {{ menu.icon }}"></i></td>
                            <td>
                                <a href="{% url 'rbac:menu_edit' menu.pk %}"><i class="fa fa-edit"></i></a>
                                <a href="{% url 'rbac:delete' 'menu' menu.pk %}"
                                ><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>

        </div>
        <div class="col-sm-9">

            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-cubes"></i> 权限管理
                    <a  href="{% url 'rbac:multi_permissions' %}" class="btn btn-sm btn-primary pull-right" style="padding: 2px 7px;margin-top: -2px"> <i
                            class="fa fa-mail-forward"></i> 批量操作</a>
                    <a href="{% url 'rbac:permission_add' %}" class="btn btn-sm btn-success pull-right"
                       style="padding: 2px 7px;margin-top: -2px"> <i
                            class="fa fa-plus-circle"></i> 添加</a>

                </div>
                <table class="table  table-hover">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>URL</th>
                        <th>URL别名</th>
                        <th>菜单</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody class="permission-area">

                    {% for permission in all_permissions.values %}
                        <tr class="root" id="{{ permission.id }}">
                            <td><i class="fa fa-caret-down"></i> {{ permission.title }}</td>
                            <td>{{ permission.url }}</td>
                            <td>{{ permission.name }}</td>
                            <td> {% if permission.menu_id %}是{% endif %}</td>
                            <td>{{ permission.menu__title|default:'' }}</td>

                            <td>
                                <a href="{% url 'rbac:permission_edit' permission.id %}"><i class="fa fa-edit"></i></a>
                                <a href="{% url 'rbac:delete' 'permission' permission.id %}"
                                ><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                        {% for c_permission in permission.children %}
                            <tr pid="{{ c_permission.parent_id }}">
                                <td>{{ c_permission.title }}</td>
                                <td>{{ c_permission.url }}</td>
                                <td>{{ c_permission.name }}</td>
                                <td> {% if c_permission.menu_id %}是{% endif %}</td>
                                <td>{{ c_permission.menu__title|default:'' }}</td>

                                <td>
                                    <a href="{% url 'rbac:permission_edit' c_permission.id %}"><i
                                            class="fa fa-edit"></i></a>
                                    <a href="{% url 'rbac:delete' 'permission' c_permission.id %}"
                                    ><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>

    </div>


{% endblock %}


{% block js %}

    <script>
        $('.root').click(function () {
            var id = $(this).attr('id');
            $("[pid=" + id + "]").toggleClass('hidden')
            var i = $(this).find('i').eq(0)
            if (i.hasClass('fa-caret-down')) {
                i.removeClass('fa-caret-down').addClass('fa-caret-right')
            } else {
                i.removeClass('fa-caret-right').addClass('fa-caret-down')

            }
        })

    </script>

{% endblock %}

day79/luffy_permission/rbac/templates/rbac/multi_permissions.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form method="post" action="?type=add">
            {% csrf_token %}
            {{ add_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-binoculars" aria-hidden="true"></i> 待新建权限列表
                    <button class="right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        新建
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：路由系统中自动发现且数据库中不存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in add_formset %}

                        <tr>
                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menu }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <i class="fa fa-th-list" aria-hidden="true"></i> 待删除权限列表
            </div>
            <div class="panel-body" style="color: #9d9d9d;">
                注意：数据库中存在，但路由系统中不存在的路由。
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>所属菜单</th>
                    <th>父权限</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for form in del_formset %}

                    <tr>
                        {{ form.id }}

                        <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                        <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                        <td>{{ form.url }}</td>
                        <td>{{ form.name }}</td>
                        <td>{{ form.parent }}</td>
                        <td>{{ form.menu }}</td>
                        <td>
                            <a href="{% url 'rbac:delete' 'permission' form.id.value %}" style="color:#d9534f;">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <form method="post" action="?type=update">
            {% csrf_token %}
            {{ update_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-sitemap" aria-hidden="true"></i> 待更新权限列表
                    <button class="right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        更新
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：数据库和路由系统都存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in update_formset %}
                        <tr>
                            {{ form.id }}

                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menu }}</td>
                            <td>
                                <a href="{% url 'rbac:delete' 'permission' form.id.value %}" style="color:#d9534f;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>
    </div>
{% endblock %}

day79/luffy_permission/rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}


{% block content %}

    <a href="{% url 'rbac:role_add' %}" class="btn btn-sm btn-success"> 添加</a>

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>序号</th>
            <th>id</th>
            <th>名称</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>

        {% for role in all_roles %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ role.pk }}</td>
                <td>{{ role.name }}</td>
                <td>
                    <a href="{% url 'rbac:role_edit' role.pk %}" class="btn btn-sm btn-info">编辑</a>
                    <a href="{% url 'rbac:delete' 'role' role.pk %}" class="btn btn-sm btn-danger">删除</a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

{% endblock %}